const { CommandParser, attach } = require("./index.js")

test("Should error when creating an instance with no prefix", () => {
  expect(() => {new CommandParser({})}).toThrow(Error)
})
test("Should have a 'help' command generated by default", () => {
  var cparse = new CommandParser({prefix: "!"})
  expect(cparse.commands).arrayContaining(
    expect.ObjectContaining({
      name: expect.toBe("help"),
      description: expect.toBe("Displays the help message.")
    })
  )
})
